import os, sqlite3, time, subprocess, json
from openai import OpenAI

DB=os.environ["OCLAW_DB_PATH"]
FACTORY="/Users/doyopc/AI/openclaw-factory"
MODEL=os.environ.get("OPENAI_MODEL","gpt-5-mini")
client=OpenAI()

def sh(cmd, cwd=FACTORY):
    r=subprocess.run(cmd, cwd=cwd, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, text=True)
    return r.stdout.strip() if r.returncode == 0 else ""

def list_targets():
    out=sh(["git","ls-files"])
    files=[x for x in out.splitlines() if x.endswith(".py") and (x.startswith("bots/") or x.startswith("scripts/"))]
    deny=(
        ".bak", "__pycache__", "archive/", "logs/", "tmp/",
        "innovation_engine_v1.py", "innovation_llm_engine_v1.py"
    )
    files=[x for x in files if not any(d in x for d in deny)]
    return files[:300]

def read_text(path, limit=6000):
    try:
        with open(os.path.join(FACTORY, path), "r", encoding="utf-8") as f:
            return f.read(limit)
    except:
        return ""

def recent_titles(con, n=120):
    rows=con.execute("""
    select lower(coalesce(title,''))
    from dev_proposals
    order by id desc
    limit ?
    """,(n,)).fetchall()
    return {r[0] for r in rows if r[0]}

def recent_targets(con, n=120):
    rows=con.execute("""
    select lower(coalesce(target_system,''))
    from dev_proposals
    order by id desc
    limit ?
    """,(n,)).fetchall()
    return {r[0] for r in rows if r[0]}

def ask_llm(path, code):
    prompt=f"""
You are improving an autonomous AI software company.
Read the target file and propose ONE concrete, low-risk improvement.

Return strict JSON only:
{{
  "title": "...",
  "description": "...",
  "category": "reliability|performance|observability|self_healing|safety|automation|analysis",
  "improvement_type": "bugfix|refactor|optimization|guard|logging|automation|diagnostics",
  "priority": 0-100,
  "quality_score": 0-1,
  "score": 0-100
}}

Rules:
- Be specific to the file content.
- Avoid vague titles.
- Avoid duplicate-like titles such as only "Improve diagnostics".
- Prefer a small concrete change.
- Mention expected effect in description.
- No markdown.
- JSON only.

Target path:
{path}

Code:
{code}
""".strip()

    r=client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role":"system","content":"You generate precise engineering improvement proposals in strict JSON."},
            {"role":"user","content":prompt},
        ],
        response_format={"type":"json_object"},
    )
    txt=r.choices[0].message.content
    data=json.loads(txt)
    return {
        "title": str(data.get("title","")).strip()[:140],
        "description": str(data.get("description","")).strip()[:2000],
        "category": str(data.get("category","analysis")).strip()[:40] or "analysis",
        "improvement_type": str(data.get("improvement_type","diagnostics")).strip()[:40] or "diagnostics",
        "priority": int(float(data.get("priority",60))),
        "quality_score": float(data.get("quality_score",0.72)),
        "score": float(data.get("score",72)),
    }

def clamp(row):
    row["priority"]=max(0,min(100,row["priority"]))
    row["quality_score"]=max(0,min(1,row["quality_score"]))
    row["score"]=max(0,min(100,row["score"]))
    if not row["title"]:
        row["title"]="Improve reliability in target module"
    if not row["description"]:
        row["description"]="AI generated concrete low-risk improvement proposal."
    return row

def main():
    con=sqlite3.connect(DB, timeout=30)
    con.execute("pragma busy_timeout=30000")
    seen_titles=recent_titles(con)
    seen_targets=recent_targets(con)
    targets=list_targets()
    inserted=0

    for path in targets:
        if path.lower() in seen_targets:
            continue
        code=read_text(path, 7000)
        if not code.strip():
            continue
        try:
            row=clamp(ask_llm(path, code))
        except Exception as e:
            print(repr(e), flush=True)
            continue

        if row["title"].lower() in seen_titles:
            continue

        con.execute("""
        insert into dev_proposals(
            title,description,branch_name,status,
            category,target_system,improvement_type,
            priority,quality_score,score,spec,source_ai,confidence
        ) values(?,?,?,?,?,?,?,?,?,?,?,?,?)
        """,(
            row["title"],
            row["description"],
            "",
            "approved",
            row["category"],
            path,
            row["improvement_type"],
            row["priority"],
            row["quality_score"],
            row["score"],
            "auto generated by innovation_llm_engine_v1",
            "innovation_llm_engine_v1",
            row["quality_score"]
        ))
        con.commit()
        seen_titles.add(row["title"].lower())
        seen_targets.add(path.lower())
        inserted += 1
        print(f"innovation_llm_created target={path} title={row['title']}", flush=True)
        if inserted >= 2:
            break

    con.close()

while True:
    try:
        main()
    except Exception as e:
        print(repr(e), flush=True)
    time.sleep(300)
