import os, sqlite3, time, random, subprocess

DB=os.environ["OCLAW_DB_PATH"]
FACTORY="/Users/doyopc/AI/openclaw-factory"

CATS=[
    ("reliability","Improve error handling in {name}","reliability"),
    ("performance","Optimize polling behavior in {name}","performance"),
    ("observability","Add structured logging to {name}","observability"),
    ("self_healing","Add recovery path to {name}","self_healing"),
    ("safety","Add guard checks to {name}","safety"),
    ("automation","Automate routine work around {name}","automation"),
    ("analysis","Improve diagnostics for {name}","analysis"),
]

def sh(cmd):
    r=subprocess.run(cmd,cwd=FACTORY,stdout=subprocess.PIPE,stderr=subprocess.DEVNULL,text=True)
    return r.stdout.splitlines() if r.returncode==0 else []

def list_targets():
    files=sh(["git","ls-files"])
    files=[x for x in files if x.endswith(".py") and (x.startswith("bots/") or x.startswith("scripts/"))]
    return files[:400]

def recent_titles(con):
    rows=con.execute("""
    select lower(title)
    from dev_proposals
    order by id desc
    limit 80
    """).fetchall()
    return {r[0] for r in rows}

def build_one(target):
    cat,title_tmpl,improvement_type=random.choice(CATS)
    name=os.path.basename(target)
    title=title_tmpl.format(name=name)
    desc=f"AI generated proposal targeting {target}. category={cat}. improve {name} with a concrete, low-risk change."
    return {
        "title": title[:120],
        "description": desc,
        "category": cat,
        "target_system": target,
        "improvement_type": improvement_type,
        "branch_name": "",
        "status": "approved",
        "priority": random.choice([40,50,60,70]),
        "quality_score": random.choice([0.62,0.68,0.74,0.81]),
        "score": random.choice([55,60,68,74,80]),
        "spec": "auto generated by innovation_engine_v1"
    }

def main():
    targets=list_targets()
    if not targets:
        return
    con=sqlite3.connect(DB,timeout=30)
    con.execute("pragma busy_timeout=30000")
    seen=recent_titles(con)

    inserted=0
    random.shuffle(targets)
    for target in targets:
        row=build_one(target)
        if row["title"].lower() in seen:
            continue
        con.execute("""
        insert into dev_proposals(
            title,description,branch_name,status,
            category,target_system,improvement_type,
            priority,quality_score,score,spec
        ) values(?,?,?,?,?,?,?,?,?,?,?)
        """,(
            row["title"],row["description"],row["branch_name"],row["status"],
            row["category"],row["target_system"],row["improvement_type"],
            row["priority"],row["quality_score"],row["score"],row["spec"]
        ))
        inserted += 1
        print(f"innovation_created target={target} title={row['title']}", flush=True)
        if inserted >= 3:
            break

    con.commit()
    con.close()

while True:
    try:
        main()
    except Exception as e:
        print(repr(e), flush=True)
    time.sleep(180)
